In [28]:
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'notebook.services'

In [ ]:
#Question 1
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
#Question 2
len(df)

9704

In [10]:
#question 3
len(df['fuel_type'].unique())

2

In [27]:
#question 4
df['num_doors'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
9699     True
9700    False
9701    False
9702    False
9703    False
Name: num_doors, Length: 9704, dtype: bool

In [43]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [44]:
a[2]

np.int64(3)

In [49]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [59]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.array([